# Generated by Django 5.2.4 on 2025-08-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0003_extrato_transacao_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categorizacao_manual',
            field=models.BooleanField(default=False),
        ),
    ]
